# Generated by Django 5.0.2 on 2024-03-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='short_description',
            field=models.CharField(blank=True, help_text="Attachment's (very) short description (max 50 characters)", max_length=50, null=True, verbose_name='Short Description'),
        ),
    ]
