# Generated by Django 5.0.2 on 2024-03-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_attachment_short_description'),
        ('thematic', '0003_theme_alter_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='themes',
            field=models.ManyToManyField(blank=True, help_text='Themes of the article.', related_name='articles', to='thematic.theme', verbose_name='Themes'),
        ),
    ]
