# Generated by Django 5.0.2 on 2024-04-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(help_text='Article ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
