# Generated by Django 5.0.6 on 2024-05-16 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_id'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Attachment',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='attachment',
                    table='files_attachment',
                ),
            ],
        ),
    ]
