# Generated by Django 5.0.2 on 2024-02-28 08:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, default=None, max_length=200, null=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name="Nom de l'organisation")),
                ('type', models.CharField(max_length=100, verbose_name="Type d'organisation")),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=core.models.organization_logo_path)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter_x', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, default=None, max_length=300, null=True, unique=True)),
                ('lastname', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Nom de famille')),
                ('firstname', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Prénom')),
                ('pseudonym', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True, verbose_name='Pseudonyme')),
                ('biography', models.TextField(blank=True, default=None, null=True, verbose_name='Biographie')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Courriel')),
                ('facebook', models.URLField(blank=True, default=None, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, default=None, null=True, verbose_name='Instagram')),
                ('twitter_x', models.URLField(blank=True, default=None, null=True, verbose_name='Twitter/X')),
                ('website', models.URLField(blank=True, default=None, null=True, verbose_name='Site web')),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to=core.models.person_picture_path, verbose_name='Photo')),
                ('organizations', models.ManyToManyField(blank=True, default=None, to='core.organization')),
            ],
            options={
                'ordering': ['lastname', 'firstname'],
            },
        ),
    ]
