# Generated by Django 5.0 on 2024-01-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_slug_alter_organization_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(blank=True, default=None, help_text='Laissez vide pour générer automatiquement.', max_length=100, null=True, unique=True),
        ),
    ]
