# Generated by Django 4.2.8 on 2023-12-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organization_facebook_organization_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='image',
            field=models.ImageField(upload_to='images/orga/'),
        ),
    ]
