# Generated by Django 5.0.2 on 2024-02-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_organization_slug'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Author',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('lastname', models.CharField(max_length=100)),
                        ('firstname', models.CharField(max_length=100)),
                        ('biography', models.TextField(blank=True)),
                        ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='interactive_maps/authors/pictures')),
                        ('organization', models.ManyToManyField(blank=True, default=None, to='core.organization')),
                    ],
                ),
            ],

            # Table already exists. See interactive_maps/migrations/0005_alter_map_introduction.py
            database_operations = [],
        )
    ]
