# Generated by Django 5.0.2 on 2024-02-12 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_author'),
        ('interactive_maps', '0006_move_author_to_core_app'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Person',
        ),
    ]
