# Generated by Django 4.2.8 on 2023-12-24 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_organization_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='image',
            new_name='logo',
        ),
    ]
