# Generated by Django 5.0 on 2024-01-01 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(help_text="L'ID de la ville.", primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Le nom de la ville.', max_length=255, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
            },
        ),
        migrations.CreateModel(
            name='MapLayer',
            fields=[
                ('id', models.AutoField(help_text="L'ID de la couche de carte.", primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Le nom de la couche de carte.', max_length=255, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Couche de carte',
                'verbose_name_plural': 'Couches de carte',
            },
        ),
        migrations.CreateModel(
            name='MapRender',
            fields=[
                ('id', models.AutoField(help_text="L'ID de la carte.", primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Le nom de la carte.', max_length=255, verbose_name='Nom')),
                ('embed_html', models.FileField(default=None, help_text='Le code HTML de la carte.', null=True, upload_to='map_data/map_renders/embed', verbose_name='Code HTML de la carte qui peut être intégré dans une page web')),
                ('full_html', models.FileField(default=None, help_text='Le code HTML complet de la carte.', null=True, upload_to='map_data/map_renders/full', verbose_name='Code HTML complet de la carte ouvrable dans un navigateur')),
            ],
            options={
                'verbose_name': 'Rendu de carte',
                'verbose_name_plural': 'Rendus de carte',
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(help_text="L'ID du GeoJSON.", primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(help_text='Le type de feature du GeoJSON.', max_length=255, verbose_name='Type de feature')),
                ('geometry_type', models.CharField(blank=True, default=None, help_text='Le type de géométrie du GeoJSON.', max_length=255, null=True, verbose_name='Type de géométrie')),
                ('geometry_coordinates', models.JSONField(blank=True, default=None, help_text='Les coordonnées de la géométrie du GeoJSON.', null=True, verbose_name='Coordonnées de la géométrie')),
                ('properties', models.JSONField(blank=True, default=None, help_text='Les propriétés du GeoJSON.', null=True, verbose_name='Propriétés')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'GeoJSON',
                'verbose_name_plural': 'GeoJSONs',
            },
        ),
    ]
