# Generated by Django 5.0 on 2024-01-10 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_data', '0001_initial'),
        ('shapes', '0002_copy_data_from_shapes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shape',
        ),
    ]
