# Generated by Django 5.0.2 on 2024-02-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_data', '0002_delete_shape'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='MapLayer',
        ),
    ]
