# Generated by Django 5.0.2 on 2024-02-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_maps', '0008_maprender_alter_map_map_render'),
        ('map_data', '0003_delete_city_delete_maplayer'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='MapRender',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='MapRender',
                    table='interactive_maps_maprender',
                ),
            ],
        ),
    ]
