# Generated by Django 5.0 on 2024-01-01 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('map_data', '0001_initial'),
        ('map_thematics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('biography', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='interactive_maps/authors/pictures')),
                ('organization', models.ManyToManyField(blank=True, default=None, to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('authors', models.ManyToManyField(blank=True, to='interactive_maps.author')),
                ('map_render', models.ForeignKey(blank=True, help_text='Le rendu de carte généré par le serveur.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='map_data.maprender', verbose_name='Rendu de carte')),
                ('thematics', models.ManyToManyField(blank=True, to='map_thematics.thematic')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('map', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='interactive_maps.map')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=100, null=True)),
                ('content', models.TextField()),
                ('order', models.IntegerField()),
                ('text', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='interactive_maps.text')),
            ],
        ),
    ]
