# Generated by Django 5.0.2 on 2024-03-05 20:32

import django.db.models.deletion
from django.db import migrations, models

# ======================================================================================================================
# Migration functions
# ======================================================================================================================

def forward_maprender_to_render(apps, schema_editor):
    Map = apps.get_model('interactive_maps', 'Map')
    for map in Map.objects.all():
        map.render = map.map_render
        map.save()
# End def forward_maprender_to_render

def backward_render_to_maprender(apps, schema_editor):
    Map = apps.get_model('interactive_maps', 'Map')
    for map in Map.objects.all():
        map.map_render = map.render
        map.save()
# End def backward_render_to_maprender

# ======================================================================================================================
# Migration
# ======================================================================================================================


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_maps', '0001_initial'),
        ('map_templates', '0009_tooltip_tooltipfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'ordering': ['id'], 'verbose_name': 'Carte interactive', 'verbose_name_plural': 'Cartes interactives'},
        ),
        migrations.AddField(
            model_name='map',
            name='render',
            field=models.OneToOneField(blank=True, help_text='Le rendu de la carte.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map', to='interactive_maps.maprender', verbose_name='Rendu de carte'),
        ),
        # Copy the data from the old map_render field to the new render field
        migrations.RunPython(
            code=forward_maprender_to_render,
            reverse_code=backward_render_to_maprender
        ),
        migrations.RemoveField(
            model_name='map',
            name='map_render',
        ),
        migrations.AlterField(
            model_name='maprender',
            name='template',
            field=models.OneToOneField(default=None, help_text='Le modèle utilisé pour générer le rendu de la carte.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='render', to='map_templates.maptemplate', verbose_name='Modèle'),
        ),
    ]
# End class Migration
