# Generated by Django 5.0 on 2024-01-02 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_maps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='map',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
