# Generated by Django 5.0 on 2024-01-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_maps', '0002_remove_text_map_delete_section_delete_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='text',
            field=models.TextField(blank=True, default=None, help_text='Le texte de la carte interactive. Formaté en HTML.', null=True),
        ),
    ]
