# Generated by Django 5.0 on 2024-01-02 23:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_maps', '0003_map_text'),
        ('map_thematics', '0002_remove_thematic_text_thematic_long_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='La date de création de la carte interactive.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='introduction',
            field=models.TextField(blank=True, default=None, help_text="L'introduction de la carte interactive. Formaté en HTML.", null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='last_modified',
            field=models.DateField(auto_now=True, help_text='La date de dernière modification de la carte interactive.'),
        ),
        migrations.AddField(
            model_name='map',
            name='slug',
            field=models.SlugField(blank=True, default=None, help_text="Le slug de la carte interactive. S'il n'est pas renseigné, il sera généré automatiquement.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='authors',
            field=models.ManyToManyField(blank=True, help_text='Les auteurs de la carte interactive.', to='interactive_maps.author'),
        ),
        migrations.AlterField(
            model_name='map',
            name='thematics',
            field=models.ManyToManyField(blank=True, help_text='Les thématiques de la carte interactive.', to='map_thematics.thematic'),
        ),
    ]
