# Generated by Django 5.0.2 on 2024-03-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_maps', '0003_rename_thematics_map_themes'),
        ('thematic', '0003_theme_alter_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='themes',
            field=models.ManyToManyField(blank=True, help_text='The themes of the map.', related_name='maps', to='thematic.theme', verbose_name='Themes'),
        ),
    ]
