# Generated by Django 5.0 on 2024-01-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_maps', '0004_map_created_at_map_introduction_map_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='introduction',
            field=models.TextField(blank=True, default=None, help_text="L'introduction de la carte interactive. Formaté en HTML.Seuls les balises de style (strong, em, etc.) seront conservées.Toutes balises de structure (section, article, h1, p, etc.) seront supprimées.", null=True),
        ),
    ]
