# Generated by Django 5.0.2 on 2024-03-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_maps', '0004_alter_map_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='The publication status of the map.', max_length=20, verbose_name='Publication status'),
        ),
    ]
