# Generated by Django 5.0.2 on 2024-03-29 16:03

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_maps', '0005_map_publication_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='text',
            new_name='body',
        ),
        migrations.AlterField(
            model_name='map',
            name='body',
            field=tinymce.models.HTMLField(blank=True, default=None, help_text='The body of the interactive map.', null=True),
        ),
    ]
