# Generated by Django 5.0.2 on 2024-02-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_author'),
        ('interactive_maps', '0005_alter_map_introduction'),
    ]

    operations = [

        # Manual Edit: Instead of deleting the model and the database for `Author`, we move it to the `core` app.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Author',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='author',
                    table='core_author',
                ),
            ]
        ),


        # Make the field `authors` in the `Map` model refer to the `core.Author` model.
        migrations.AlterField(
            model_name='map',
            name='authors',
            field=models.ManyToManyField(blank=True, help_text='Les auteurs de la carte interactive.', to='core.author'),
        ),
    ]
