# Generated by Django 5.0.2 on 2024-04-26 07:55

import django.db.models.deletion
import interactive_maps.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_organization_name_alter_organization_type_and_more'),
        ('interactive_maps', '0006_rename_text_map_body_alter_map_body'),
        ('map_templates', '0009_tooltip_tooltipfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'ordering': ['id'], 'verbose_name': 'Interactive Map', 'verbose_name_plural': 'Interactive Maps'},
        ),
        migrations.AlterModelOptions(
            name='maprender',
            options={'verbose_name': 'Map Render', 'verbose_name_plural': 'Map Renders'},
        ),
        migrations.AlterField(
            model_name='map',
            name='authors',
            field=models.ManyToManyField(blank=True, help_text='The authors of the map.', to='core.person', verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='map',
            name='body',
            field=tinymce.models.HTMLField(blank=True, default=None, help_text='The body of the interactive map. Formatted in HTML.', null=True, verbose_name='Body text'),
        ),
        migrations.AlterField(
            model_name='map',
            name='created_at',
            field=models.DateField(auto_now_add=True, help_text='The creation date of the interactive map.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='map',
            name='introduction',
            field=models.TextField(blank=True, default=None, help_text='The introduction of the interactive map. Formatted in HTML.Only style tags (strong, em, etc.) will be kept.All structure tags (section, article, h1, p, etc.) will be removed.', null=True, verbose_name='Introduction text'),
        ),
        migrations.AlterField(
            model_name='map',
            name='last_modified',
            field=models.DateField(auto_now=True, help_text='The last modification date of the interactive map.', verbose_name='Last modified'),
        ),
        migrations.AlterField(
            model_name='map',
            name='render',
            field=models.OneToOneField(blank=True, help_text='The render of the map.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map', to='interactive_maps.maprender', verbose_name='Render'),
        ),
        migrations.AlterField(
            model_name='map',
            name='slug',
            field=models.SlugField(blank=True, default=None, help_text='The slug of the map. This field is automatically generated from the title.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maprender',
            name='embed_html',
            field=models.FileField(default=None, help_text='The embedded HTML code of the map. This file is used for the embedded display of the map.', null=True, upload_to=interactive_maps.models.map_render_embed_path, verbose_name='Embedded HTML'),
        ),
        migrations.AlterField(
            model_name='maprender',
            name='full_html',
            field=models.FileField(default=None, help_text='The full HTML code of the map. This file is used for the fullscreen display of the map.', null=True, upload_to=interactive_maps.models.map_render_full_path, verbose_name='Full HTML'),
        ),
        migrations.AlterField(
            model_name='maprender',
            name='id',
            field=models.AutoField(help_text='The unique identifier of the map render.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='maprender',
            name='name',
            field=models.CharField(help_text='The name of the map render.', max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='maprender',
            name='template',
            field=models.OneToOneField(default=None, help_text='The template used to render the map.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='render', to='map_templates.maptemplate', verbose_name='Template'),
        ),
    ]
