# Generated by Django 5.0.6 on 2024-05-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_unique_together_alter_file_slug_and_more'),
        ('interactive_maps', '0007_alter_map_options_alter_maprender_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='attachments',
            field=models.ManyToManyField(blank=True, help_text='Files attached to the interactive map.', related_name='interactive_maps', to='files.file', verbose_name='Attached files'),
        ),
    ]
