# Generated by Django 5.0.2 on 2024-02-17 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_maps', '0007_alter_map_authors'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations = [
                migrations.CreateModel(
                    name='MapRender',
                    fields=[
                        ('id', models.AutoField(help_text="L'ID de la carte.", primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(help_text='Le nom de la carte.', max_length=255, verbose_name='Nom')),
                        ('embed_html', models.FileField(default=None, help_text='Le code HTML de la carte.', null=True, upload_to='map_data/map_renders/embed', verbose_name='Code HTML de la carte qui peut être intégré dans une page web')),
                        ('full_html', models.FileField(default=None, help_text='Le code HTML complet de la carte.', null=True, upload_to='map_data/map_renders/full', verbose_name='Code HTML complet de la carte ouvrable dans un navigateur')),
                    ],
                    options={
                        'verbose_name': 'Rendu de carte',
                        'verbose_name_plural': 'Rendus de carte',
                    },
                ),
            ],
            # The table already exists and will be moved from the `map_data` application.
            # See the `0004_delete_maprender` migration for details.
            database_operations=[],
        ),

        # This migration is generated to alter the `map_render` field of the `Map` model.
        # Since the `MapRender` model is moved from the `map_data` application, the `map_render` field
        # of the `Map` model must be altered to point to the new location of the `MapRender` model.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='map',
                    name='map_render',
                    field=models.ForeignKey(blank=True, help_text='Le rendu de carte généré par le serveur.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='interactive_maps.maprender', verbose_name='Rendu de carte'),
                ),
            ],
            database_operations=[],
        ),
    ]
