# Generated by Django 5.0.6 on 2024-05-21 13:18

import interactive_maps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_maps', '0008_map_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='thumbnail',
            field=models.ImageField(default=None, help_text='The thumbnail to be displayed on the map card.', null=True, upload_to=interactive_maps.models.thumbnail_path, verbose_name='Thumbnail'),
        ),
        migrations.AddField(
            model_name='map',
            name='thumbnail_attributions',
            field=models.TextField(default=None, help_text='The attributions to be given to the thumbnail. May include the author, the source, etc. Formatted in HTML.', null=True, verbose_name="Thumbnail's attributions"),
        ),
        migrations.AddField(
            model_name='map',
            name='thumbnail_license',
            field=models.CharField(choices=[('cc-by-4.0', 'CC BY 4.0'), ('cc-by-3.0', 'CC BY 3.0'), ('cc-by-2.5', 'CC BY 2.5'), ('cc-by-2.0', 'CC BY 2.0'), ('cc-by-1.0', 'CC BY 1.0'), ('cc-by-sa-4.0', 'CC BY-SA 4.0'), ('cc-by-sa-3.0', 'CC BY-SA 3.0'), ('cc-by-sa-2.5', 'CC BY-SA 2.5'), ('cc-by-sa-2.0', 'CC BY-SA 2.0'), ('cc-by-sa-1.0', 'CC BY-SA 1.0'), ('cc-by-nc-4.0', 'CC BY-NC 4.0'), ('cc-by-nc-3.0', 'CC BY-NC 3.0'), ('cc-by-nc-2.5', 'CC BY-NC 2.5'), ('cc-by-nc-2.0', 'CC BY-NC 2.0'), ('cc-by-nc-1.0', 'CC BY-NC 1.0'), ('cc-by-nc-sa-4.0', 'CC BY-NC-SA 4.0'), ('cc-by-nc-sa-3.0', 'CC BY-NC-SA 3.0'), ('cc-by-nc-sa-2.5', 'CC BY-NC-SA 2.5'), ('cc-by-nc-sa-2.0', 'CC BY-NC-SA 2.0'), ('cc-by-nc-sa-1.0', 'CC BY-NC-SA 1.0'), ('cc-by-nd-4.0', 'CC BY-ND 4.0'), ('cc-by-nd-3.0', 'CC BY-ND 3.0'), ('cc-by-nd-2.5', 'CC BY-ND 2.5'), ('cc-by-nd-2.0', 'CC BY-ND 2.0'), ('cc-by-nd-1.0', 'CC BY-ND 1.0'), ('cc-by-nc-nd-4.0', 'CC BY-NC-ND 4.0'), ('cc-by-nc-nd-3.0', 'CC BY-NC-ND 3.0'), ('cc-by-nc-nd-2.5', 'CC BY-NC-ND 2.5'), ('cc-by-nc-nd-2.0', 'CC BY-NC-ND 2.0'), ('cc-by-nc-nd-1.0', 'CC BY-NC-ND 1.0'), ('all-rights-reserved', 'All rights reserved'), ('public-domain', 'Public domain'), ('unknown', 'Unknown'), ('no-copyright', 'No copyright')], default=None, help_text='The license of the thumbnail.', null=True, verbose_name="Thumbnail's license"),
        ),
        migrations.AddField(
            model_name='map',
            name='thumbnail_source',
            field=models.URLField(default=None, help_text='The source of the thumbnail.', max_length=255, null=True, verbose_name="Thumbnail's source"),
        ),
    ]
