# Generated by Django 5.0.2 on 2024-02-17 11:00

import interactive_maps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_maps', '0008_maprender_alter_map_map_render'),
        ('map_data', '0004_delete_maprender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maprender',
            name='embed_html',
            field=models.FileField(default=None, help_text='Le code HTML de la carte pouvant être intégré dans une page web.', null=True, upload_to=interactive_maps.models.map_render_embed_path, verbose_name='HTML intégrable'),
        ),
        migrations.AlterField(
            model_name='maprender',
            name='full_html',
            field=models.FileField(default=None, help_text="Le code HTML d'une page web contenant la carte.", null=True, upload_to=interactive_maps.models.map_render_full_path, verbose_name='HTML complet'),
        ),
    ]
