# Generated by Django 5.0.6 on 2024-05-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_maps', '0009_map_thumbnail_map_thumbnail_attributions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='thumbnail_attributions',
            field=models.TextField(blank=True, default=None, help_text='The attributions to be given to the thumbnail. May include the author, the source, etc. Formatted in HTML.', null=True, verbose_name="Thumbnail's attributions"),
        ),
        migrations.AlterField(
            model_name='map',
            name='thumbnail_license',
            field=models.CharField(choices=[('cc-by-4.0', 'CC BY 4.0'), ('cc-by-3.0', 'CC BY 3.0'), ('cc-by-2.5', 'CC BY 2.5'), ('cc-by-2.0', 'CC BY 2.0'), ('cc-by-1.0', 'CC BY 1.0'), ('cc-by-sa-4.0', 'CC BY-SA 4.0'), ('cc-by-sa-3.0', 'CC BY-SA 3.0'), ('cc-by-sa-2.5', 'CC BY-SA 2.5'), ('cc-by-sa-2.0', 'CC BY-SA 2.0'), ('cc-by-sa-1.0', 'CC BY-SA 1.0'), ('cc-by-nc-4.0', 'CC BY-NC 4.0'), ('cc-by-nc-3.0', 'CC BY-NC 3.0'), ('cc-by-nc-2.5', 'CC BY-NC 2.5'), ('cc-by-nc-2.0', 'CC BY-NC 2.0'), ('cc-by-nc-1.0', 'CC BY-NC 1.0'), ('cc-by-nc-sa-4.0', 'CC BY-NC-SA 4.0'), ('cc-by-nc-sa-3.0', 'CC BY-NC-SA 3.0'), ('cc-by-nc-sa-2.5', 'CC BY-NC-SA 2.5'), ('cc-by-nc-sa-2.0', 'CC BY-NC-SA 2.0'), ('cc-by-nc-sa-1.0', 'CC BY-NC-SA 1.0'), ('cc-by-nd-4.0', 'CC BY-ND 4.0'), ('cc-by-nd-3.0', 'CC BY-ND 3.0'), ('cc-by-nd-2.5', 'CC BY-ND 2.5'), ('cc-by-nd-2.0', 'CC BY-ND 2.0'), ('cc-by-nd-1.0', 'CC BY-ND 1.0'), ('cc-by-nc-nd-4.0', 'CC BY-NC-ND 4.0'), ('cc-by-nc-nd-3.0', 'CC BY-NC-ND 3.0'), ('cc-by-nc-nd-2.5', 'CC BY-NC-ND 2.5'), ('cc-by-nc-nd-2.0', 'CC BY-NC-ND 2.0'), ('cc-by-nc-nd-1.0', 'CC BY-NC-ND 1.0'), ('all-rights-reserved', 'All rights reserved'), ('public-domain', 'Public domain'), ('unknown', 'Unknown'), ('no-copyright', 'No copyright')], default='unknown', help_text='The license of the thumbnail.', verbose_name="Thumbnail's license"),
        ),
        migrations.AlterField(
            model_name='map',
            name='thumbnail_source',
            field=models.URLField(blank=True, default=None, help_text='The source of the thumbnail.', max_length=255, null=True, verbose_name="Thumbnail's source"),
        ),
    ]
