# Generated by Django 5.0.2 on 2024-03-03 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_layers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maplayercustomproperty',
            name='map_layer',
        ),
        migrations.DeleteModel(
            name='MapLayer',
        ),
        migrations.DeleteModel(
            name='MapLayerCustomProperty',
        ),
    ]
