# Generated by Django 5.0 on 2024-01-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_layers', '0004_maplayer_maplayercustomproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente de génération'), ('GENERATING', 'Génération en cours'), ('DONE', 'Génération terminée'), ('ERROR', 'Erreur lors de la génération')], default='PENDING', help_text='Statut de la couche.', max_length=20, verbose_name='Statut'),
        ),
    ]
