# Generated by Django 5.0.2 on 2024-02-12 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_layers', '0007_alter_city_limits_dataset_alter_maplayer_dataset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maplayer',
            name='encoding',
        ),
    ]
