# Generated by Django 5.0.2 on 2024-02-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_layers', '0009_delete_city_delete_citydatasetkeyvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='generation_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échoué')], default='PENDING', help_text='Statut de la génération des géométries de la couche.', max_length=10, verbose_name='Statut de la génération'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='task_id',
            field=models.CharField(blank=True, default=None, help_text='ID de la tâche asynchrone utilisée pour générer les géométries de la couche.', max_length=100, null=True, verbose_name='ID de la tâche'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='regenerate',
            field=models.BooleanField(default=False, help_text='Relance la génération des géométries de la couche.', verbose_name='Regénérer'),
        ),
    ]
