# Generated by Django 5.0.2 on 2024-02-11 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tilelayer',
            name='url',
            field=models.URLField(blank=True, default=None, help_text="L'URL 'XYZ' de la tuile de carte.", max_length=500, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='tilelayer',
            name='name',
            field=models.CharField(help_text='Nom de la tuile de carte.', max_length=100, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='tilelayer',
            name='verbose_name',
            field=models.CharField(blank=True, default=None, help_text="Le nom d'affichage de la tuile de carte. Laisser vide pour utiliser le nom par défaut.", max_length=100, null=True, unique=True, verbose_name="Nom d'affichage"),
        ),
        migrations.AlterModelOptions(
            name='propertystyle',
            options={'verbose_name': 'Style de propriété', 'verbose_name_plural': 'Styles des propriétés'},
        ),
        migrations.AlterField(
            model_name='layer',
            name='highlight',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlight_of', to='map_templates.style'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='style',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='style_of', to='map_templates.style'),
        ),
    ]
