# Generated by Django 5.0.2 on 2024-02-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_templates', '0002_alter_tilelayer_url_alter_tilelayer_name_and_more_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='maptemplate',
            name='generation_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échoué')], default='PENDING', help_text='Statut de la génération du rendu de la carte.', max_length=10, verbose_name='Statut de la génération'),
        ),
        migrations.AddField(
            model_name='maptemplate',
            name='regenerate',
            field=models.BooleanField(default=False, help_text='Relance la génération du rendu de la carte.', verbose_name='Regénérer'),
        ),
        migrations.AddField(
            model_name='maptemplate',
            name='task_id',
            field=models.CharField(blank=True, default=None, help_text='ID de la tâche asynchrone utilisée pour générer le rendu de la carte.', max_length=100, null=True, verbose_name='ID de la tâche'),
        ),
    ]
