# Generated by Django 5.0.2 on 2024-02-24 20:24

import map_templates.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_templates', '0003_maptemplate_generation_status_maptemplate_regenerate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertystyle',
            name='dash_array',
            field=models.CharField(blank=True, default=None, help_text='Chaîne de charactères définissant le motif de la bordure des formes.', max_length=50, null=True, validators=[map_templates.validators.validate_dash_array]),
        ),
        migrations.AlterField(
            model_name='style',
            name='dash_array',
            field=models.CharField(blank=True, default=None, help_text='Chaîne de charactères définissant le motif de la bordure des formes.', max_length=50, null=True, validators=[map_templates.validators.validate_dash_array]),
        ),
    ]
