# Generated by Django 5.0.2 on 2024-03-03 21:21

import colorfield.fields
import django.core.validators
import map_templates.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_templates', '0003_remove_maptemplate_generation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertystyle',
            name='fill_opacity',
        ),
        migrations.RemoveField(
            model_name='propertystyle',
            name='opacity',
        ),
        migrations.RemoveField(
            model_name='style',
            name='fill_opacity',
        ),
        migrations.RemoveField(
            model_name='style',
            name='opacity',
        ),
        migrations.AlterField(
            model_name='propertystyle',
            name='color',
            field=colorfield.fields.ColorField(default='#3388ffff', help_text='La couleur des bordures des formes.', image_field=None, max_length=25, samples=None, verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='propertystyle',
            name='dash_array',
            field=models.CharField(blank=True, default=None, help_text='Motif des Pointillés.', max_length=50, null=True, validators=[map_templates.validators.validate_dash_array], verbose_name='Pointillés'),
        ),
        migrations.AlterField(
            model_name='propertystyle',
            name='dash_offset',
            field=models.CharField(blank=True, default=None, help_text='Espacements des Pointillés.', max_length=5, null=True, verbose_name='Espacement des pointillés'),
        ),
        migrations.AlterField(
            model_name='propertystyle',
            name='fill',
            field=models.BooleanField(default=True, help_text='Indique si les formes doivent être remplies.', verbose_name='Remplissage'),
        ),
        migrations.AlterField(
            model_name='propertystyle',
            name='fill_color',
            field=colorfield.fields.ColorField(blank=True, default='#3388ff33', help_text='La couleur de remplissage des formes. Si non défini, la couleur de bordure est utilisée.', image_field=None, max_length=25, null=True, samples=None, verbose_name='Couleur de remplissage'),
        ),
        migrations.AlterField(
            model_name='propertystyle',
            name='fill_rule',
            field=models.CharField(choices=[('nonzero', 'Nonzero'), ('evenodd', 'Evenodd')], default='evenodd', help_text='La règle de remplissage des formes.', max_length=100, verbose_name='Règle de remplissage'),
        ),
        migrations.AlterField(
            model_name='propertystyle',
            name='line_cap',
            field=models.CharField(choices=[('butt', 'Plate'), ('round', 'Ronde'), ('square', 'Carrée')], default='round', help_text='La terminaison des bordures des formes.', max_length=6, verbose_name='Terminaison'),
        ),
        migrations.AlterField(
            model_name='propertystyle',
            name='stroke',
            field=models.BooleanField(default=True, help_text='Indique si les bordures des formes doivent être dessinées.', verbose_name='Bordures'),
        ),
        migrations.AlterField(
            model_name='propertystyle',
            name='weight',
            field=models.FloatField(default=3, help_text="L'épaisseur des bordures des formes (en pixels).", validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Épaisseur'),
        ),
        migrations.AlterField(
            model_name='style',
            name='color',
            field=colorfield.fields.ColorField(default='#3388ffff', help_text='La couleur des bordures des formes.', image_field=None, max_length=25, samples=None, verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='style',
            name='dash_array',
            field=models.CharField(blank=True, default=None, help_text='Motif des Pointillés.', max_length=50, null=True, validators=[map_templates.validators.validate_dash_array], verbose_name='Pointillés'),
        ),
        migrations.AlterField(
            model_name='style',
            name='dash_offset',
            field=models.CharField(blank=True, default=None, help_text='Espacements des Pointillés.', max_length=5, null=True, verbose_name='Espacement des pointillés'),
        ),
        migrations.AlterField(
            model_name='style',
            name='fill',
            field=models.BooleanField(default=True, help_text='Indique si les formes doivent être remplies.', verbose_name='Remplissage'),
        ),
        migrations.AlterField(
            model_name='style',
            name='fill_color',
            field=colorfield.fields.ColorField(blank=True, default='#3388ff33', help_text='La couleur de remplissage des formes. Si non défini, la couleur de bordure est utilisée.', image_field=None, max_length=25, null=True, samples=None, verbose_name='Couleur de remplissage'),
        ),
        migrations.AlterField(
            model_name='style',
            name='fill_rule',
            field=models.CharField(choices=[('nonzero', 'Nonzero'), ('evenodd', 'Evenodd')], default='evenodd', help_text='La règle de remplissage des formes.', max_length=100, verbose_name='Règle de remplissage'),
        ),
        migrations.AlterField(
            model_name='style',
            name='line_cap',
            field=models.CharField(choices=[('butt', 'Plate'), ('round', 'Ronde'), ('square', 'Carrée')], default='round', help_text='La terminaison des bordures des formes.', max_length=6, verbose_name='Terminaison'),
        ),
        migrations.AlterField(
            model_name='style',
            name='stroke',
            field=models.BooleanField(default=True, help_text='Indique si les bordures des formes doivent être dessinées.', verbose_name='Bordures'),
        ),
        migrations.AlterField(
            model_name='style',
            name='weight',
            field=models.FloatField(default=3, help_text="L'épaisseur des bordures des formes (en pixels).", validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Épaisseur'),
        ),
        migrations.AlterField(
            model_name='propertystyle',
            name='line_join',
            field=models.CharField(choices=[('arcs', 'Arcs'), ('bevel', 'Bevel'), ('miter', 'Miter'), ('miter-clip', 'Miter-clip'), ('round', 'Round')], default='round', help_text='La jonction des bordures des formes.', max_length=10, verbose_name='Jonction'),
        ),
        migrations.AlterField(
            model_name='style',
            name='line_join',
            field=models.CharField(choices=[('arcs', 'Arcs'), ('bevel', 'Bevel'), ('miter', 'Miter'), ('miter-clip', 'Miter-clip'), ('round', 'Round')], default='round', help_text='La jonction des bordures des formes.', max_length=10, verbose_name='Jonction'),
        ),
    ]
