# Generated by Django 5.0.2 on 2024-03-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_templates', '0004_remove_propertystyle_fill_opacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='boundary_type',
            field=models.CharField(choices=[('intersect', 'Intersection'), ('strict', 'Stricte'), ('crop', 'Recadrement')], default='intersect', help_text='Le type de délimitation de la couche cartographique.', max_length=15, verbose_name='Type de délimitation'),
        ),
    ]
