# Generated by Django 5.0.2 on 2024-03-04 21:45

import colorfield.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_templates', '0005_layer_boundary_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CirclePattern',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', colorfield.fields.ColorField(default='#000000FF', help_text='La couleur des bandes.', image_field=None, max_length=25, samples=None, verbose_name='Couleur des Bandes')),
                ('width', models.IntegerField(default=4, help_text='Distance (horizontale) entre les cercles', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Distance horizontale')),
                ('height', models.IntegerField(default=4, help_text='Distance (verticale) entre les cercles', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Distance verticale')),
                ('radius', models.IntegerField(default=12, help_text='Le rayon des cercles (en pixels).', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Rayon')),
                ('fill_color', colorfield.fields.ColorField(default='#3388FF33', help_text='La couleur de remplissage des cercles.', image_field=None, max_length=25, samples=None, verbose_name='Couleur de remplissage')),
            ],
            options={
                'verbose_name': 'Motif en cercle',
                'verbose_name_plural': 'Motifs en cercle',
            },
        ),
        migrations.CreateModel(
            name='StripePattern',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', colorfield.fields.ColorField(default='#000000FF', help_text='La couleur des bandes.', image_field=None, max_length=25, samples=None, verbose_name='Couleur des Bandes')),
                ('space_color', colorfield.fields.ColorField(default='#FFFFFFFF', help_text="La couleur de l'espace entre les bandes.", image_field=None, max_length=25, samples=None, verbose_name='Couleur des Espaces')),
                ('weight', models.IntegerField(default=4, help_text='La largeur des bandes (en pixels).', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Largeur')),
                ('space_weight', models.IntegerField(default=4, help_text="La largeur de l'espace entre les bandes (en pixels).", validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Largeur des espaces')),
                ('angle', models.FloatField(default=0.5, help_text="L'angle des bandes (en degrés).", validators=[django.core.validators.MinValueValidator(-360.0), django.core.validators.MaxValueValidator(360.0)], verbose_name='Angle')),
            ],
            options={
                'verbose_name': 'Motif à rayures',
                'verbose_name_plural': 'Motifs à rayures',
            },
        ),
        migrations.AlterModelOptions(
            name='style',
            options={'verbose_name': 'Style', 'verbose_name_plural': 'Styles'},
        ),
        migrations.AddField(
            model_name='propertystyle',
            name='circle_pattern',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='map_templates.circlepattern'),
        ),
        migrations.AddField(
            model_name='style',
            name='circle_pattern',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='map_templates.circlepattern'),
        ),
        migrations.AddField(
            model_name='propertystyle',
            name='stripe_pattern',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='map_templates.stripepattern'),
        ),
        migrations.AddField(
            model_name='style',
            name='stripe_pattern',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='map_templates.stripepattern'),
        ),
    ]
