# Generated by Django 5.0.2 on 2024-03-05 13:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0005_alter_datasetlayer_name_alter_datasetlayerfield_name'),
        ('map_templates', '0008_featuregroup_z_index_layer_z_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tooltip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sticky', models.BooleanField(default=True, help_text='Si le tooltip doit suivre le curseur de la souris.', verbose_name='Collant')),
                ('style', models.TextField(blank=True, default=None, help_text='Le style du tooltip, défini en CSS.', null=True, verbose_name='Style')),
                ('layer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tooltip', to='map_templates.layer')),
            ],
            options={
                'verbose_name': 'Infobulle',
                'verbose_name_plural': 'Infobulles',
            },
        ),
        migrations.CreateModel(
            name='TooltipField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text="L'alias du champ dans l'infobulle.", max_length=255)),
                ('index', models.IntegerField(default=0, help_text="L'index de l'infobulle.", validators=[django.core.validators.MinValueValidator(0)], verbose_name='Index')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.datasetlayerfield')),
                ('tooltip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='map_templates.tooltip')),
            ],
            options={
                'verbose_name': "Champ d'infobulle",
                'verbose_name_plural': "Champs d'infobulles",
                'unique_together': {('tooltip', 'field')},
            },
        ),
    ]
