# Generated by Django 5.0.6 on 2024-10-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_templates', '0010_alter_circlepattern_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuregroup',
            name='display',
            field=models.BooleanField(default=True, help_text='Whether the feature group is displayed. If not displayed, the feature group is ignored during rendering.', verbose_name='Display'),
        ),
        migrations.AddField(
            model_name='layer',
            name='display',
            field=models.BooleanField(default=True, help_text='Whether the layer is displayed. If not displayed, the layer is ignored during rendering.', verbose_name='Display'),
        ),
    ]
