# Generated by Django 5.0.2 on 2024-03-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_maps', '0002_alter_map_options_remove_map_map_render_map_render_and_more'),
        ('thematic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thematic',
            new_name='Theme',
        ),
    ]
