# Generated by Django 5.0.2 on 2024-03-21 17:42

import colorfield.fields
import thematic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thematic', '0002_rename_thematic_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='slug',
            field=models.SlugField(blank=True, default=None, help_text='Slug of the theme, used in urls.', max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(help_text='Name of the theme.', max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='short_name',
            field=models.CharField(blank=True, help_text='Short name of the theme, used for tags.', max_length=20, null=True, unique=True, verbose_name='Short name'),
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='short_desc',
            new_name='summary',
        ),
        migrations.AlterField(
            model_name='theme',
            name='summary',
            field=models.CharField(blank=True, help_text='Short description of the theme, displayed on the theme index page.', max_length=200, null=True, verbose_name='Summary'),
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='long_desc',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=models.TextField(blank=True, help_text='Long description of the theme, displayed on the theme page as an article.', null=True, verbose_name='Description'),
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='splash_img',
            new_name='cover_image',
        ),
        migrations.AlterField(
            model_name='theme',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Image displayed on the theme page.', null=True, upload_to=thematic.models.get_theme_cover_path, verbose_name='Cover image'),
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='splash_color',
            new_name='color',
        ),
        migrations.AlterField(
            model_name='theme',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Color used to represent the theme.', image_field=None, max_length=25, null=True, samples=None, verbose_name='Color'),
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Theme', 'verbose_name_plural': 'Themes'},
        ),
    ]
