# Generated by Django 5.0.6 on 2024-05-17 06:35

import django.db.models.deletion
import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_delete_attachment'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attachment',
            new_name='File',
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.AutoField(help_text="File's ID", primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='file',
            name='article',
            field=models.ForeignKey(help_text='Article to which the file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='articles.article', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(help_text='Verbose name of the file', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('file', 'File'), ('pdf', 'PDF'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], default=None, help_text='The type of file attached. Will be calculated automatically if left empty.', max_length=10, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(help_text='The file to upload to the website.', max_length=500, upload_to=files.models.get_upload_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='file',
            name='short_description',
            field=models.CharField(blank=True, help_text='A (very) short description of the file (max 50 characters, optional)', max_length=50, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
    ]
