# Generated by Django 5.0.6 on 2024-05-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_rename_attachment_file_alter_file_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='file',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.RemoveField(
            model_name='file',
            name='article',
        ),
    ]
