# Generated by Django 5.0 on 2024-01-10 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(help_text="L'ID de la géométrie GeoJSON.", primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(help_text='Le type de feature du GeoJSON.', max_length=255, verbose_name='Type de feature')),
                ('geometry_type', models.CharField(blank=True, default=None, help_text='Le type de géométrie du GeoJSON.', max_length=255, null=True, verbose_name='Type de géométrie')),
                ('geometry_coordinates', models.JSONField(blank=True, default=None, help_text='Les coordonnées de la géométrie du GeoJSON.', null=True, verbose_name='Coordonnées de la géométrie')),
                ('properties', models.JSONField(blank=True, default=None, help_text='Les propriétés du GeoJSON.', null=True, verbose_name='Propriétés')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Geometrie GeoJSON',
                'verbose_name_plural': 'Geometries GeoJSON',
            },
        ),
    ]
