# Generated by Django 5.0.2 on 2024-02-28 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map_layers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(help_text="L'ID de la géométrie GeoJSON.", primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(help_text='Le type de feature du GeoJSON.', max_length=255, verbose_name='Type de feature')),
                ('geometry_type', models.CharField(blank=True, default=None, help_text='Le type de géométrie du GeoJSON.', max_length=255, null=True, verbose_name='Type de géométrie')),
                ('geometry_coordinates', models.JSONField(blank=True, default=None, help_text='Les coordonnées de la géométrie du GeoJSON.', null=True, verbose_name='Coordonnées de la géométrie')),
                ('properties', models.JSONField(blank=True, default=None, help_text='Les propriétés du GeoJSON.', null=True, verbose_name='Propriétés')),
                ('parent_layer', models.ForeignKey(blank=True, default=None, help_text='La couche parent de la géométrie GeoJSON.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shapes', to='map_layers.maplayer', verbose_name='Couche parent')),
            ],
            options={
                'verbose_name': 'Geometrie GeoJSON',
                'verbose_name_plural': 'Geometries GeoJSON',
            },
        ),
    ]
