# Generated by Django 5.0.2 on 2024-02-14 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_layers', '0009_delete_city_delete_citydatasetkeyvalue_and_more'),
        ('shapes', '0002_copy_data_from_shapes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shape',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='object_id',
        ),
        migrations.AddField(
            model_name='shape',
            name='parent_layer',
            field=models.ForeignKey(blank=True, default=None, help_text='La couche parent de la géométrie GeoJSON.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shapes', to='map_layers.maplayer', verbose_name='Couche parent'),
        ),
    ]
